apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-app
      tier: backend
  template:
    metadata:
      labels:
        app: business-app
        tier: backend
    spec:
      containers:
      - name: business
        image: iortizf/business-ms:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8086