apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
      tier: backend
  template:
    metadata:
      labels:
        app: login-app
        tier: backend
    spec:
      containers:
      - name: login
        image: iortizf/login-ms:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8087