apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-app
      tier: backend
  template:
    metadata:
      labels:
        app: actions-app
        tier: backend
    spec:
      containers:
      - name: account
        image: iortizf/actions-ms:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8085