apiVersion: v1
kind: PersistentVolume
metadata:
  name: actions-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/lib/postgresql/data/actions