apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-app
      tier: backend
  template:
    metadata:
      labels:
        app: account-app
        tier: backend
    spec:
      containers:
      - name: account
        image: iortizf/account-ms:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8085