apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-db
      tier: database
  template:
    metadata:
      labels:
        app: offer-db
        tier: database
    spec:
      containers:
      - name: offer-db
        image: mongo
        imagePullPolicy: Always
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: offer-db-volume
          mountPath: /data/offer
      volumes:
        - name: offer-db-volume
          persistentVolumeClaim:
            claimName: offer-db-pvc