apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-app
      tier: backend
  template:
    metadata:
      labels:
        app: offer-app
        tier: backend
    spec:
      containers:
      - name: offer
        image: iortizf/offer-ms:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8089